### ISSUE TITLE
App works in debug/profile but crash in release

### ISSUE THREAD

**Issue by swarupbhc** [Vonage-Community/sample-video-flutter-app#4]
Hi, when I build the app on release mode it crash on calling initSession, working perfectly on debug/release mode, here is the complete logs - https://gist.github.com/swarupbhc/0dc2ad644f15ad35d301d30bddb10f65. 

Android version - Android 13, Android 11
Logs - https://gist.github.com/swarupbhc/0dc2ad644f15ad35d301d30bddb10f65

Is there a way to fix that?
Thx.

**Comment by devwithzachary** [comment]
Thank you for the bug report. Judging by 

<table><tbody><tr><td>F/example.auction(10457): runtime.cc:683] No pending exception expected: java.lang.ClassNotFoundException: com.opentok.android.SubscriberKit$SubscriberAudioStats</td></tr><tr><td>&nbsp;</td></tr></tbody></table>

I'm going to guess that ProGuard is automatically enabled in your instant of Android studio.  
  
You can either build using the `--no-shrink ` flag when running flutter build. Or you can take a look at [https://tokbox.com/developer/sdks/android/#proguard-rules-needed-by-the-vonage-android-sdk](https://tokbox.com/developer/sdks/android/#proguard-rules-needed-by-the-vonage-android-sdk) for the ProGuard rules that need to be setup so that the Vonage SDK doesn't get shrunk.

**Comment by swarupbhc** [comment]
Thank you again @devwithzachary
